# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: The Glorious Gospel
title: The Gospel from Gravel Hill
subtitle: "…the glorious gospel of the blessed God…  —1 Timothy 1:11"
description: "A Continuation of Scott MacLeod's former site https://www.thegloriousgospel.ca/"
author: Marc MacArthur

url: "https://gospel.fromgravelhill.ca"
baseurl: ""

permalink: pretty
markdown: kramdown
theme: null

paginate: 5
paginate_path: "/page:num"
exclude: ["README.md"]

# Plugins for GitHub Pages
plugins:
  - jekyll-paginate

# Navigation structure (if you want to loop through this in nav)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Audio"
    url: "/audio/"
  - title: "Articles"
    url: "/articles/"
#  - title: "Tracts"
#    url: "/tracts/"
#  - title: "Charts"
#    url: "/charts/"
  - title: "Books"
    url: "/books/"
  - title: "Contact"
    url: "/contact/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
